main: org.ranin.rolePlay.App
name: "rolePlay"
version: 0.5.0
api-version: 1.16
authors: ["chibbi", "raninninn"]
description: "An exhaustive plugin to make roleplay servers even more enjoyable and challengin."
website: "www.spigotmc.org"
commands:
   kit:
      description: "Gives You stuff"
      permission: rolePlay.kit
   job:
      description: "lets you choose your job"
      permission: rolePlay.job
   money:
      description: "lets you manage your finances"
      permission: rolePlay.money
permissions:
   rolePlay.kit:
      description: Permission for the /kit command
      default: op
   rolePlay.job:
      description: Permission for the /job command
      default: true
   rolePlay.money:
      description: Permission for the /money command
      default: true