main: org.ranin.rolePlay.App
name: "rolePlay"
version: 0.3.0
api-version: 1.16
authors: ["chibbi", "raninninn"]
description: "An exhaustive plugin to make roleplay servers even more enjoyable and challengin."
website: "www.spigotmc.org"
commands:
   kit:
      description: "Gives You stuff"
      permission: rolePlay.kit
   job:
      description: "lets you choose your job"
      permission: rolePlay.job
   hobby:
      description: "lets you choose your job"
      permission: rolePlay.hobby
permissions:
   rolePlay.kit:
      description: Permission for the /kit command
      default: op
   rolePlay.job:
      description: Permission for the /kit command
      default: true
   rolePlay.hobby:
      description: Permission for the /kit command
      default: true