main: org.ranin.rolePlay.App
name: rolePlay
version: 0.1
description: An exhaustive plugin to make roleplay servers even more enjoyable and challengin.
authors: [chibbi, raninninn]
website: www.spigotmc.org
commands:
   kit:
      description: Gives You stuff
      usage: /kit
      permission: yourplugin.yourcommandpermission
